hobbysite/blog/urls.py
from django.urls import path
from .views import CategoryListView, ArticleDetailView, ArticleCreateView, ArticleUpdateView

urlpatterns = [
    path('blog/articles/', CategoryListView.as_view(), name="articlelist"),
    path('blog/article/<int:pk>/', ArticleDetailView.as_view(), name='article'),
    path('blog/article/create/', ArticleCreateView.as_view(), name='blog_create'),
    path('blog/article/<int:pk>/edit/', ArticleUpdateView.as_view(), name='blog_update'),
]

app_name ="blog"


hobbysite/commissions/urls.py
from django.urls import path

from .views import CommissionListView, CommissionDetailView, CommissionCreateView, CommissionUpdateView

urlpatterns = [
    path('commissions/list/', CommissionListView.as_view(), name="commissions"),
    path('commissions/detail/<int:pk>/',
         CommissionDetailView.as_view(), name="commission"),
    path('commissions/add/', CommissionCreateView.as_view(), name="commission_add"),
    path('commissions/<int:pk>/edit/',
         CommissionUpdateView.as_view(), name="commission_edit")
]

app_name = "commissions"

hobbysite/hobbysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import HomePageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('commissions.urls', namespace='commissions')),
    path('', include('wiki.urls', namespace='wiki')),
    path('merchstore/', include('merchstore.urls', namespace='merchstore')),
    path('', include('blog.urls', namespace='blog')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('profile/', include('user_management.urls', namespace="user_management")),
    path('homepage/', HomePageView.as_view(), name='homepage'),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hobbysite/merchstore/urls.py
from .views import CartView, TransactionListView, ProductCreateView, ProductUpdateView, ProductListView, ProductDetailView
from django.urls import path

urlpatterns = [
    path('items', ProductListView.as_view(), name="product_type"),
    path('item/<int:pk>', ProductDetailView.as_view(), name="product"),
    path('item/add', ProductCreateView.as_view(), name='product_create'),
    path('item/<int:pk>/edit', ProductUpdateView.as_view(), name='product_update'),
    path('cart', CartView.as_view(), name='cart'),
    path('transactions', TransactionListView.as_view(), name='transaction')
]

app_name = "merchstore"

hobbysite/wiki/urls.py
from django.urls import path
from .views import ArticleListView, ArticleDetailView, ArticleUpdateView, ArticleCreateView, image_gallery

urlpatterns = [
    path('wiki/articles/', ArticleListView.as_view(), name='articles'),
    path('wiki/article/<int:pk>', ArticleDetailView.as_view(), name='article'),
    path('wiki/article/<int:pk>/edit', ArticleUpdateView.as_view(), name='article_update'),
    path('wiki/article/add', ArticleCreateView.as_view(), name="article_add"),
    path('wiki/gallery', image_gallery, name='article_gallery'),
]

app_name = 'wiki'

hobbysite/blog/models.py
from django.db import models
from django.conf import settings
from user_management.models import Profile
from django.urls import reverse
from datetime import datetime

class ArticleCategory(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    class Meta:
        ordering = ['name']

    def __str__(self) -> str:
        return self.name
    
    def get_absolute_url(self):
        return reverse('blog:category', kwargs={'pk':self.pk})

class Article(models.Model):
    title = models.CharField(max_length=255)
    author =  models.ForeignKey(Profile, related_name='author', on_delete=models.SET_NULL, null=True, blank =True)
    category = models.ForeignKey('ArticleCategory',  related_name='category',on_delete=models.CASCADE, null=True)
    entry = models.TextField()
    header_image = models.ImageField(upload_to='images/', null=True)
    created_on = models.DateTimeField(default= datetime.now, blank=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['category__name','-created_on'] 

    def __str__(self) -> str:
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:article', kwargs={'pk':self.pk})


class Comment(models.Model):
    author =  models.ForeignKey(Profile, related_name='commentauthor',on_delete=models.SET_NULL, null=True, blank=False)
    article = models.ForeignKey(Article, related_name='article', on_delete=models.CASCADE, null=True)
    entry = models.TextField()
    created_on = models.DateTimeField(default= datetime.now, blank=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self) -> str:
        return self.entry

hobbysite/commissions/models.py
from django.db import models
from django.urls import reverse

from user_management.models import Profile


class Commission(models.Model):
    STATUS_CHOICES = (
        ('Full', 'Full'),
        ('Completed', 'Completed'),
        ('Discontinued', 'Discontinued')
    )
    title = models.CharField(max_length=255)
    description = models.TextField()
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default='Open')
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('commissions:commission', args=[self.pk])

    class Meta:
        ordering = ['created_on']


class Job(models.Model):
    STATUS_CHOICES = (
        ('Open', 'Open'),
        ('Full', 'Full')
    )
    commission = models.ForeignKey(Commission,
                                   on_delete=models.CASCADE)
    role = models.CharField(max_length=255)
    manpower_required = models.PositiveIntegerField()
    status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default='Open')

    class Meta:
        ordering = ['-status', '-manpower_required', 'role']


class JobApplication(models.Model):
    STATUS_CHOICES = (
        ('Pending', 'Pending'),
        ('Accepted', 'Accepted'),
        ('Rejected', 'Rejected')
    )
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    applicant = models.ForeignKey(Profile, on_delete=models.CASCADE)
    status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default='Pending')
    applied_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-status', '-applied_on']

hobbysite/commissions/forms.py
from django import forms

from .models import Commission, Job, JobApplication
from django.core.validators import MinValueValidator


class CommissionForm(forms.ModelForm):
    role = forms.CharField(max_length=100)
    manpower_required = forms.IntegerField(validators=[MinValueValidator(1)])

    class Meta:
        model = Commission
        # Fields from Commission model
        fields = ['title', 'description', 'status']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class JobApplicationForm(forms.ModelForm):
    class Meta:
        model = JobApplication
        # 'applicant' is automatically set to the logged-in user
        fields = ['job', 'status']

    def __init__(self, *args, **kwargs):
        super(JobApplicationForm, self).__init__(*args, **kwargs)
        self.fields['status'].initial = 'Pending'  # Initial status

hobbysite/commissions/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Commission, Job, JobApplication
from django.views import View
from typing import Any
from django.db.models import Sum
from django.db.models.query import QuerySet
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.forms import inlineformset_factory
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect

from user_management.models import Profile
from .models import Commission, JobApplication, Job
from .forms import CommissionForm


class CommissionListView(ListView):
    model = Commission
    template_name = 'commissionList.html'

    def get_queryset(self):
        queryset = Commission.objects.all().order_by('status', '-created_on')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.request.user.is_authenticated:
            user = self.request.user

            # Filter commissions where the current user is the author

            my_posted_commissions = Commission.objects.filter(
                author=user.profile).order_by('status', '-created_on')
            context['my_posted_commissions'] = my_posted_commissions

            # Filter commissions where the current user has applied
            my_applied_commissions = Commission.objects.filter(
                job__jobapplication__applicant=user.profile).order_by('status', '-created_on').distinct()
            context['my_applied_commissions'] = my_applied_commissions

            all_commissions = Commission.objects.all()
            context['all_commissions'] = all_commissions
        return context

    def post(self, request, *args, **kwargs):
        form = CommissionForm(request.POST)
        if form.is_valid():
            form.save()
            return self.get(request, *args, **kwargs)
        else:
            self.object_list = self.get_queryset(**kwargs)
            context = self.get_context_data(**kwargs)
            context['form'] = form
            return self.render_to_response(context)


class CommissionDetailView(LoginRequiredMixin, DetailView):
    model = Commission
    template_name = 'commission.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        commission = self.get_object()
        jobs = Job.objects.filter(commission=commission)

        # Calculate total manpower required
        total_manpower_required = jobs.aggregate(
            total_manpower=Sum('manpower_required'))['total_manpower'] or 0

        # Calculate total signees for all jobs
        total_signees = JobApplication.objects.filter(
            job__in=jobs, status='Accepted').count()

        # Calculate remaining open manpower
        remaining_manpower = total_manpower_required - total_signees

        # Determine if the "Apply to Job" button should be clickable for each job
        can_apply = {}
        for job in jobs:
            can_apply[job.pk] = total_signees < job.manpower_required
        is_owner = commission.author == self.request.user.profile

        context['is_owner'] = is_owner
        context['commission'] = commission
        context['jobs'] = jobs
        context['total_manpower_required'] = total_manpower_required
        context['total_signees'] = total_signees
        context['remaining_manpower'] = remaining_manpower
        context['can_apply'] = can_apply

        # Include the updated commission instance in the context
        context['commission'] = self.object

        return context

    def post(self, request, *args, **kwargs):
        job_id = request.POST.get('job_id')
        job = get_object_or_404(Job, pk=job_id)
        accepted_applicants_count = job.jobapplication_set.filter(
            status='Accepted').count()
        if accepted_applicants_count < job.manpower_required + 1:
            # Create a JobApplication object
            JobApplication.objects.create(
                job=job, applicant=request.user.profile, status='Pending')
            # increment the number of applicants
            job.jobapplication_set.create(
                applicant=request.user.profile, status='Accepted')
            return redirect('commissions:commission', pk=self.kwargs['pk'])
        else:
            # Handle the case where the job cannot be applied
            pass


class CommissionCreateView(LoginRequiredMixin, CreateView):
    model = Commission
    form_class = CommissionForm
    template_name = 'createCommission.html'

    success_url = reverse_lazy('commissions:commissions')

    def form_valid(self, form):
        commission = form.save(commit=False)
        commission.author = self.request.user.profile
        commission.save()
        job = commission.job_set.create(
            role=form.cleaned_data['role'],
            manpower_required=form.cleaned_data['manpower_required']
        )

        return super().form_valid(form)


class CommissionUpdateView(LoginRequiredMixin, UpdateView):
    model = Commission
    form_class = CommissionForm
    template_name = "updateCommission.html"

    def get_success_url(self):
        return reverse_lazy('commissions:commission', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        manpower_required = form.cleaned_data.get('manpower_required')
        role = form.cleaned_data.get('role')

        job = self.object.job_set.first()
        if job:
            job.manpower_required = manpower_required
            job.role = role
            job.save()

        return super().form_valid(form)

hobbysite/templates/article_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title%} Wiki Details{% endblock %}
{% block styles %}
<style>
    .content-box {
        background-color: antiquewhite;
        border: 1px solid #000000;
        border-radius: 5px;
        padding: 20px; /* Increased padding for more space */
        margin-bottom: 20px;
        width: 500px; /* Increased width for a larger box */
    }

    .content-box img {
        max-width: 100%;
        height: auto;
        margin-bottom: 10px;
    }

</style>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <a href="{% url 'wiki:articles' %}" class="btn btn-dark mb-3">Back to Wiki Articles List</a>
            <section class="content">
                <h2>Wiki Details</h2>
                <div class="content-box">
                    <ul>
                        <li><strong>Title:</strong> {{ article.title }}</li>
                        {% if article.image %}
                            <img src="{{ article.image.url }}" alt="{{ article.title }}">
                        {% endif %}
                        <li><strong>Entry:</strong> {{ article.entry }}</li>
                        <li><strong>Category:</strong> {{ article.articlecategory }}</li>
                        <li><strong>Created On:</strong> {{ article.created_on }}</li>
                        <li><strong>Updated On:</strong> {{ article.updated_on }}</li>
                    </ul>
                </div>

                {% if user.is_authenticated %}
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-dark">Add Comment</button>
                    </form>
                {% endif %}
                <br>

                <h5>Comments</h5> 
                {% for comment in article.comment_set.all %}
                    <p>[{{comment.created_on}}] {{ comment.author.display_name }} wrote: {{ comment.entry }}</p>
                {% endfor %}

                <h6>Articles in the same category as "{{ article.articlecategory }}"</h6>
                <ul>
                    {% for related_article in article.articlecategory.article_set.all %}
                        {% if related_article.pk != article.pk %}
                            <li><a href="{{ related_article.get_absolute_url }}">{{ related_article.title }}</a></li>
                        {% endif %}
                    {% endfor %}
                </ul>

                {% if user.is_authenticated and article.author == user.profile %}
                    <form method="GET" action="{% url 'wiki:article_update' pk=article.pk %}">
                        <button type="submit" class="btn btn-dark">Edit Article</button>
                    </form>
                {% endif %}

                <br>
                <br>

                <form method="GET" action="{% url 'wiki:article_gallery' %}">
                    <button type="submit" class="btn btn-dark">View Image Gallery</button>
                </form>
            </section>
        </div>
    </div>
</div>
{% endblock %}


hobbysite/templates/article_gallery.html
{% extends 'base.html' %} {% block content %}
<style>
    .gallery img {
        width: 500px;
        height: 500px;
        object-fit: cover;
        border-radius: 8px;
        margin: 10px;
    }
</style>
<body>
    <h1>Article Gallery</h1>
    <div class="gallery">
        {% for image_url in image_urls %}
        <img src="{{ image_url }}" alt="Article Image" />
        <ul>
            Picture: {{ image_url.title }}
        </ul>
        <hr />
        {% endfor %}
    </div>
</body>
{% endblock %}

hobbysite/templates/article_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Wiki List{% endblock %}
{% block styles %}
<style>
    .content-box {
        background-color: antiquewhite;
        border: 1px solid #000000;
        border-radius: 5px;
        padding: 20px; /* Increased padding for more space */
        margin-bottom: 20px;
        width: 500px; /* Increased width for a larger box */
    }

    .content-box img {
        max-width: 100%;
        height: auto;
        margin-bottom: 10px;
    }

</style>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 style="display: inline;">Wiki List</h1>
            <br> <br>
            <span>
                {% if user.is_authenticated %}
                    <form method="get" action="{% url 'wiki:article_add' %}">
                        <button type="submit" class="btn btn-dark"><h4>Create Article</h4></button>
                    </form>
                    <br>
                {% endif %}
            </span>
            <section class="content">
                {% for article in object_list %}
                    <div class="content-box">
                        {% if article.author.user == request.user %}
                            <strong>[Your Article]</strong> <br><br>
                        {% endif %}
                        <a href="{{ article.get_absolute_url }}"><strong>{{ article.title }}</strong></a>
                        <strong>[{{ article.articlecategory }}]</strong>
                    </div>
                {% endfor %}
            </section>
        </div>
    </div>
</div>
{% endblock %}

hobbysite/templates/blog_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <h1>Blog</h1>
{% endblock title %}
{% block styles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<style>

    .content {
        position: absolute;
        left: 100px;

        padding: 10px;
        flex-grow: 3;
        }
    a {
        color: #000000;
        
    }
    p{

        font-size: 15px; 
        color: #000000;
    }
    li{
        font-size: 15px; 
        color: #000000;
    }
    details{
        border-radius: 5px;
    }
    strong{
        font-weight: bold;
        font-size: large; 
        color: #000000;
    }

    summary {
        padding: 4px;
        width: 250px;
        background-color: #E8DFCA;
        border: none;
        box-shadow: 1px 1px 2px #bbbbbb;

        border-radius: 5px;
        border:2px solid #000000;
}
</style>
{% endblock %}
{% block content %}

<section class="content">
    <p><strong style= "font-size: 32px;">Blog Details</strong></p>
    


    {% if user.is_authenticated and article.author == user.profile %}
        <form method="GET" action="{% url 'blog:blog_update' pk=article.pk %}">
        <button type="submit" style='background-color: #E8DFCA;color: #000000; border:2px solid #000000;border-radius: 5px;'><h4>Edit Blog</h4></button>
    </form>
    {% endif %}

    <a href= "/blog/articles"><button style="background-color: #E8DFCA;color: #000000; border:2px solid #000000;border-radius: 5px;">Back to Categories</button> </a>

    <p style="font-size: x-large;"><strong>Category:</strong> {{ article.category }}</p>


    <ul>
        <p style='text-align: center; font-weight:bold; font-size: xxx-large; color: #000000' >{{ article.title }}</p>
        {% if article.header_image %}
            <p style='text-align: center;'><img src="{{ article.header_image.url }}" ></p>
        {% endif %}
        <br>
        <strong>Entry:</strong><p style="text-align: center; background-color: #E8DFCA; border-radius: 5px; padding: 15px;width: 800px;">{{ article.entry }}</p>
            <details>
                <summary><strong>Created/Update On</strong></summary>

                <p><strong style='font-size: medium;'>Created On: </strong>{{ article.created_on }}
                <br><strong style='font-size: medium;'>Updated On:</strong>{{ article.updated_on }}</p>
        </details>
    </ul>


    <h4>Similar blogs to "{{ article.category }}"</h4>
    <ul>
        {% for related_article in article.category.category.all %}
            {% if related_article.pk != article.pk %}
                <li><a href="{{ related_article.get_absolute_url }}">{{ related_article.title }}</a></li>
            {% endif %}
        {% endfor %}
    </ul>

    {% if user.is_authenticated %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" style="background-color: #E8DFCA;color: #000000; border:2px solid #000000;border-radius: 5px;">Add Comment</button>
    </form>
    {% endif %}

    <p><strong>Comments:</strong></p>
    {% for comment in article.article.all %}
            <li>{{comment.created_on}} {{ comment.author.display_name }} said: {{ comment.entry }}
            </li><br>
    {% endfor %} 
    <br><br><br>
</section>
{% endblock %}

<!-- article.comment_set.all -->

hobbysite/templates/commission.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title%} Commission Details{% endblock %}
{% block styles %}
<style>
    /* Custom styles */
    main{
        margin-left: 0px;
    }
    .commission-details {
        background-color: #f8f9fa;
        padding: 20px;
        border-radius: 5px;
        margin-bottom: 20px;
        margin-left: 150px;
    }
    .job-item {
        margin-bottom: 10px;
    }

    .colored-box {
        background-color: #333 ;
        border-radius: 10px; 
        padding: 20px;
        border: 1px solid #ced4da; 
        color: antiquewhite;
    }

    .btn-color{
        background-color: antiquewhite;
        color: #333;
    }

    .btn-color:hover{
        background-color:antiquewhite;
        color: #333;
        border-color: black; 
    }
    main a:link{
        color: #333;
    }
    main a:visited{
        color: #333;
    }

</style>
{% endblock %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="commission-details colored-box">
                <h1>{{ commission.title }}</h1>
                <p>Description: {{ commission.description }}</p>
                <p>Total Manpower Required: {{ total_manpower_required }}</p>
                <h2>Jobs</h2>
                <ul class="list-unstyled">
                    {% for job in jobs %}
                        <li class="job-item">
                            <strong>{{ job.role }}</strong> - Manpower Required: {{ remaining_manpower }}
                            {% if can_apply|get_item:job.pk %}
                                <form method="post" action="{% url 'commissions:commission' pk=job.commission.pk %}">
                                    {% csrf_token %}
                                    <input type="hidden" name="job_id" value="{{ job.pk }}">
                                    <button type="submit" class="btn btn-primary btn-color">Apply to Job</button>
                                </form>
                            {% else %}
                                <button class="btn btn-primary btn-color" disabled>Apply to Job</button>
                                {% if total_signees >= total_manpower_required %}
                                    <p>This job is currently full.</p>
                                {% endif %}
                            {% endif %}
                        </li>
                    {% endfor %}
                </ul>
                {% if is_owner %}
                    <a href="{% url 'commissions:commission_edit' commission.pk %}" class="btn btn-secondary btn-color">Edit Commission</a>
                {% endif %}
                <a href="/commissions/list/" class="btn btn-secondary btn-color">Back to Commissions List</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

hobbysite/templates/items_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Products
{% endblock title %}
{% block styles %}
<style>
    main{
        margin-left: 0px;
    }
    .button {
        background-color: black; 
        color: white;
        padding: 15px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        border-radius: 10px;
        cursor: pointer;
        transition: 0.3s;
    }
    .button:hover {
        background-color:white;
        color: black;
        border-color: black; 
    }
    a {
        color:#333;
        text-decoration:none;
        }

    .headbar {
        background-color:black;
        color: #fff;
        padding: 10px 200px;
        text-align: center;
        word-wrap: break-word;
     }

    .typebar {
        background-color: black;
        color: #fff;
        padding: 0px;
        text-align: center;
        font-family:Verdana, sans-serif;
        word-wrap: break-word;
    }

    .product-box {
        background-color: lightgray;
        color: black;
        box-sizing: border-box;
        padding: 5px;
        margin-bottom: 10px;
        cursor: pointer;
        border-style: solid;
        border-radius: 10px;
        border-color: black;
        transition: 0.3s;
    }

    .product-box:hover {
        background-color: white;
        color: black;
        border-color: black;
    }
</style>
{% endblock styles%}
{% block content %}
<h1 class = "headbar">Products</h1>
    <h2>
        <p style="font-size: 36pt; margin-right: 15px;">
    {% if user.is_authenticated %}
        <h2>Your Products</h2>
            <p>
                <a href=/merchstore/transactions><button class="button">View your sold items</button></a>
                <a href="{% url 'merchstore:product_create' %}"><button class="button">Create A Product</button></a>
                <a href="{% url 'merchstore:cart' %}"><button class="button">Cart</button></a>
            </p>
            {% for product_type in object_list %}
                    <p class = "typebar">
                        {{ product_type.name }}
                    </p>
                    {% for product in my_products %}
                        {% if product.product_type == product_type %}
                        <a href="{{ product.get_absolute_url }}">
                            <div class ="product-box">
                                {{ product }} - {{ product.status }}
                            </div>
                        </a>
                        <p> PHP {{ product.price }}</p>
                        {% endif %}
                    {% endfor %}
            {% endfor %}
            <h2>All Products</h2>
                {% if object_list.exists %}
                    {% for product_type in object_list %}
                            <p class = "typebar">
                                {{ product_type.name }}
                            </p>
                        {% for product in product_type.products.all %}
                            {% if product.author != request.user.profile %}
                                <a href="{{ product.get_absolute_url }}">
                                    <div class ="product-box">
                                        {{ product }} - {{ product.status }}
                                    </div>
                                </a>
                                <p> PHP {{ product.price }}</p>
                            {% endif %}
                        {% endfor %}
                    {% endfor %}
                {% else %}
                    <p>No products under this categories.</p>
                {% endif %}
    {% else %}
        <h2>All Products</h2>
            {% for product_type in object_list %}
                <p class = "typebar">
                    {{ product_type.name }}
                </p>
                {% for product in product_type.products.all %}
                    <a href="{{ product.get_absolute_url }}">
                        <div class ="product-box">
                            {{ product }} - {{ product.status }}
                        </div>
                    </a>
                    <p> PHP {{ product.price }}</p>
                {% endfor %}
            {% endfor %}
    {% endif %}
{% endblock content %}

hobbysite/templates/updateCommission.html
{% extends 'base.html' %}
{% block title %}Update Commission and Jobs{% endblock %}
{% block content %}
<style>
    .container-custom {
        background-color: #333;
        color:antiquewhite;
        padding: 20px;
        border-radius: 10px;
        margin-top: 20px;
        max-width: 600px;
        margin: 0 auto;
        border: 1px solid #ced4da;
    }

    .form-control {
        border: 1px solid #ced4da;
        border-radius: 5px;
        padding: 10px 15px;
        width: 100%;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
    }

    .form-control:focus {
        border-color: #80bdff;
        outline: none;
        box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
    }

    .form-label {
        font-weight: bold;
    }

    h2,
    label {
        color: antiquewhite;
    }
    .btn{
        margin-top: 20px;
    }
    .btn-color {
        background-color: antiquewhite;
        color: #333;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s ease-in-out;
    }

    .btn-color:hover {
        background-color: #333;
        color: antiquewhite;
        border: 1px solid antiquewhite;
    }
</style>

<div class="container mt-5 container-custom">
    <h2>Update Commission and Job</h2>
    <form method="POST" action="{% url 'commissions:commission_edit' pk=form.instance.pk %}">
        {% csrf_token %}
        {{ form.as_p }} {# Render commission form fields #}
        <table>
            {% for form in job_formset %}
            {{ form.as_table }}
            {% endfor %}
        </table>
        <button type="submit" class="btn btn-color">Update</button>
    </form>
</div>
{% endblock %}